name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: contact_list_ci_cd_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Setup database
        run: |
          cp config/database.yml.github-actions config/database.yml
          RAILS_ENV=test bundle exec rails db:create
          RAILS_ENV=test bundle exec rails db:schema:load

      - name: Run tests
        run: |
          RAILS_ENV=test bundle exec rails test
